### ISSUE TITLE
ward-incharge_l.h.s_customization

### ISSUE THREAD

**Issue by vinutha012** [Kteamworks/KDemo_base#133]

**Comment by PavithraSrinivas** [comment]
What changes is needed??

**Comment by vinutha012** [comment]
In demo_test...ward incharge screen on l.h.s ...all d options r
available...as if admin screen...basically oly options which r relevant t
ward incharge shud be available...

On 09-Feb-2018 5:07 pm, "PavithraSrinivas" <notifications@github.com> wrote:

What changes is needed??

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kteamworks/KDemo_base/issues/133#issuecomment-364411025>,
or mute the thread
